/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TemperatureUnit = IDL.Variant({
  'fahrenheit' : IDL.Null,
  'celsius' : IDL.Null,
});
export const WeatherAlert = IDL.Record({
  'description' : IDL.Text,
  'weatherCode' : IDL.Nat,
  'severity' : IDL.Text,
});
export const CurrentConditions = IDL.Record({
  'temperature' : IDL.Float64,
  'unit' : TemperatureUnit,
  'weatherDescription' : IDL.Text,
  'pressure' : IDL.Float64,
  'windSpeed' : IDL.Float64,
  'humidity' : IDL.Float64,
  'windDirection' : IDL.Float64,
  'feelsLike' : IDL.Float64,
  'weatherCode' : IDL.Nat,
});
export const DailyForecast = IDL.Record({
  'date' : IDL.Text,
  'tempMax' : IDL.Float64,
  'tempMin' : IDL.Float64,
  'weatherDescription' : IDL.Text,
  'windSpeed' : IDL.Float64,
  'weatherCode' : IDL.Nat,
  'precipitationProbability' : IDL.Float64,
});
export const GeoLocation = IDL.Record({
  'latitude' : IDL.Float64,
  'country' : IDL.Text,
  'name' : IDL.Text,
  'longitude' : IDL.Float64,
});
export const WeatherResponse = IDL.Record({
  'alerts' : IDL.Vec(WeatherAlert),
  'current' : CurrentConditions,
  'forecast' : IDL.Vec(DailyForecast),
  'location' : GeoLocation,
});
export const WeatherError = IDL.Variant({
  'cityNotFound' : IDL.Null,
  'parseError' : IDL.Text,
  'apiError' : IDL.Text,
});
export const WeatherResult = IDL.Variant({
  'ok' : WeatherResponse,
  'err' : WeatherError,
});
export const SearchCityResult = IDL.Variant({
  'ok' : IDL.Vec(GeoLocation),
  'err' : WeatherError,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'getWeather' : IDL.Func([IDL.Text, TemperatureUnit], [WeatherResult], []),
  'searchCity' : IDL.Func([IDL.Text], [SearchCityResult], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TemperatureUnit = IDL.Variant({
    'fahrenheit' : IDL.Null,
    'celsius' : IDL.Null,
  });
  const WeatherAlert = IDL.Record({
    'description' : IDL.Text,
    'weatherCode' : IDL.Nat,
    'severity' : IDL.Text,
  });
  const CurrentConditions = IDL.Record({
    'temperature' : IDL.Float64,
    'unit' : TemperatureUnit,
    'weatherDescription' : IDL.Text,
    'pressure' : IDL.Float64,
    'windSpeed' : IDL.Float64,
    'humidity' : IDL.Float64,
    'windDirection' : IDL.Float64,
    'feelsLike' : IDL.Float64,
    'weatherCode' : IDL.Nat,
  });
  const DailyForecast = IDL.Record({
    'date' : IDL.Text,
    'tempMax' : IDL.Float64,
    'tempMin' : IDL.Float64,
    'weatherDescription' : IDL.Text,
    'windSpeed' : IDL.Float64,
    'weatherCode' : IDL.Nat,
    'precipitationProbability' : IDL.Float64,
  });
  const GeoLocation = IDL.Record({
    'latitude' : IDL.Float64,
    'country' : IDL.Text,
    'name' : IDL.Text,
    'longitude' : IDL.Float64,
  });
  const WeatherResponse = IDL.Record({
    'alerts' : IDL.Vec(WeatherAlert),
    'current' : CurrentConditions,
    'forecast' : IDL.Vec(DailyForecast),
    'location' : GeoLocation,
  });
  const WeatherError = IDL.Variant({
    'cityNotFound' : IDL.Null,
    'parseError' : IDL.Text,
    'apiError' : IDL.Text,
  });
  const WeatherResult = IDL.Variant({
    'ok' : WeatherResponse,
    'err' : WeatherError,
  });
  const SearchCityResult = IDL.Variant({
    'ok' : IDL.Vec(GeoLocation),
    'err' : WeatherError,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'getWeather' : IDL.Func([IDL.Text, TemperatureUnit], [WeatherResult], []),
    'searchCity' : IDL.Func([IDL.Text], [SearchCityResult], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };