/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CurrentConditions {
  'temperature' : number,
  'unit' : TemperatureUnit,
  'weatherDescription' : string,
  'pressure' : number,
  'windSpeed' : number,
  'humidity' : number,
  'windDirection' : number,
  'feelsLike' : number,
  'weatherCode' : bigint,
}
export interface DailyForecast {
  'date' : string,
  'tempMax' : number,
  'tempMin' : number,
  'weatherDescription' : string,
  'windSpeed' : number,
  'weatherCode' : bigint,
  'precipitationProbability' : number,
}
export interface GeoLocation {
  'latitude' : number,
  'country' : string,
  'name' : string,
  'longitude' : number,
}
export type SearchCityResult = { 'ok' : Array<GeoLocation> } |
  { 'err' : WeatherError };
export type TemperatureUnit = { 'fahrenheit' : null } |
  { 'celsius' : null };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface WeatherAlert {
  'description' : string,
  'weatherCode' : bigint,
  'severity' : string,
}
export type WeatherError = { 'cityNotFound' : null } |
  { 'parseError' : string } |
  { 'apiError' : string };
export interface WeatherResponse {
  'alerts' : Array<WeatherAlert>,
  'current' : CurrentConditions,
  'forecast' : Array<DailyForecast>,
  'location' : GeoLocation,
}
export type WeatherResult = { 'ok' : WeatherResponse } |
  { 'err' : WeatherError };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'getWeather' : ActorMethod<[string, TemperatureUnit], WeatherResult>,
  'searchCity' : ActorMethod<[string], SearchCityResult>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];