/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface GeoLocation {
    latitude: number;
    country: string;
    name: string;
    longitude: number;
}
export type WeatherError = {
    __kind__: "cityNotFound";
    cityNotFound: null;
} | {
    __kind__: "parseError";
    parseError: string;
} | {
    __kind__: "apiError";
    apiError: string;
};
export interface WeatherResponse {
    alerts: Array<WeatherAlert>;
    current: CurrentConditions;
    forecast: Array<DailyForecast>;
    location: GeoLocation;
}
export interface WeatherAlert {
    description: string;
    weatherCode: bigint;
    severity: string;
}
export type WeatherResult = {
    __kind__: "ok";
    ok: WeatherResponse;
} | {
    __kind__: "err";
    err: WeatherError;
};
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface DailyForecast {
    date: string;
    tempMax: number;
    tempMin: number;
    weatherDescription: string;
    windSpeed: number;
    weatherCode: bigint;
    precipitationProbability: number;
}
export interface CurrentConditions {
    temperature: number;
    unit: TemperatureUnit;
    weatherDescription: string;
    pressure: number;
    windSpeed: number;
    humidity: number;
    windDirection: number;
    feelsLike: number;
    weatherCode: bigint;
}
export type SearchCityResult = {
    __kind__: "ok";
    ok: Array<GeoLocation>;
} | {
    __kind__: "err";
    err: WeatherError;
};
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export enum TemperatureUnit {
    fahrenheit = "fahrenheit",
    celsius = "celsius"
}
export interface backendInterface {
    getWeather(city: string, unit: TemperatureUnit): Promise<WeatherResult>;
    searchCity(city: string): Promise<SearchCityResult>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
}
import type { CurrentConditions as _CurrentConditions, DailyForecast as _DailyForecast, GeoLocation as _GeoLocation, SearchCityResult as _SearchCityResult, TemperatureUnit as _TemperatureUnit, WeatherAlert as _WeatherAlert, WeatherError as _WeatherError, WeatherResponse as _WeatherResponse, WeatherResult as _WeatherResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getWeather(arg0: string, arg1: TemperatureUnit): Promise<WeatherResult> {
        if (this.processError) {
            try {
                const result = await this.actor.getWeather(arg0, to_candid_TemperatureUnit_n1(this._uploadFile, this._downloadFile, arg1));
                return from_candid_WeatherResult_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWeather(arg0, to_candid_TemperatureUnit_n1(this._uploadFile, this._downloadFile, arg1));
            return from_candid_WeatherResult_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchCity(arg0: string): Promise<SearchCityResult> {
        if (this.processError) {
            try {
                const result = await this.actor.searchCity(arg0);
                return from_candid_SearchCityResult_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchCity(arg0);
            return from_candid_SearchCityResult_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
}
function from_candid_CurrentConditions_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CurrentConditions): CurrentConditions {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_SearchCityResult_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SearchCityResult): SearchCityResult {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_TemperatureUnit_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TemperatureUnit): TemperatureUnit {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_WeatherError_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WeatherError): WeatherError {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_WeatherResponse_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WeatherResponse): WeatherResponse {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_WeatherResult_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WeatherResult): WeatherResult {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    alerts: Array<_WeatherAlert>;
    current: _CurrentConditions;
    forecast: Array<_DailyForecast>;
    location: _GeoLocation;
}): {
    alerts: Array<WeatherAlert>;
    current: CurrentConditions;
    forecast: Array<DailyForecast>;
    location: GeoLocation;
} {
    return {
        alerts: value.alerts,
        current: from_candid_CurrentConditions_n7(_uploadFile, _downloadFile, value.current),
        forecast: value.forecast,
        location: value.location
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    temperature: number;
    unit: _TemperatureUnit;
    weatherDescription: string;
    pressure: number;
    windSpeed: number;
    humidity: number;
    windDirection: number;
    feelsLike: number;
    weatherCode: bigint;
}): {
    temperature: number;
    unit: TemperatureUnit;
    weatherDescription: string;
    pressure: number;
    windSpeed: number;
    humidity: number;
    windDirection: number;
    feelsLike: number;
    weatherCode: bigint;
} {
    return {
        temperature: value.temperature,
        unit: from_candid_TemperatureUnit_n9(_uploadFile, _downloadFile, value.unit),
        weatherDescription: value.weatherDescription,
        pressure: value.pressure,
        windSpeed: value.windSpeed,
        humidity: value.humidity,
        windDirection: value.windDirection,
        feelsLike: value.feelsLike,
        weatherCode: value.weatherCode
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fahrenheit: null;
} | {
    celsius: null;
}): TemperatureUnit {
    return "fahrenheit" in value ? TemperatureUnit.fahrenheit : "celsius" in value ? TemperatureUnit.celsius : value;
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cityNotFound: null;
} | {
    parseError: string;
} | {
    apiError: string;
}): {
    __kind__: "cityNotFound";
    cityNotFound: null;
} | {
    __kind__: "parseError";
    parseError: string;
} | {
    __kind__: "apiError";
    apiError: string;
} {
    return "cityNotFound" in value ? {
        __kind__: "cityNotFound",
        cityNotFound: value.cityNotFound
    } : "parseError" in value ? {
        __kind__: "parseError",
        parseError: value.parseError
    } : "apiError" in value ? {
        __kind__: "apiError",
        apiError: value.apiError
    } : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_GeoLocation>;
} | {
    err: _WeatherError;
}): {
    __kind__: "ok";
    ok: Array<GeoLocation>;
} | {
    __kind__: "err";
    err: WeatherError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_WeatherError_n11(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _WeatherResponse;
} | {
    err: _WeatherError;
}): {
    __kind__: "ok";
    ok: WeatherResponse;
} | {
    __kind__: "err";
    err: WeatherError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_WeatherResponse_n5(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_WeatherError_n11(_uploadFile, _downloadFile, value.err)
    } : value;
}
function to_candid_TemperatureUnit_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TemperatureUnit): _TemperatureUnit {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TemperatureUnit): {
    fahrenheit: null;
} | {
    celsius: null;
} {
    return value == TemperatureUnit.fahrenheit ? {
        fahrenheit: null
    } : value == TemperatureUnit.celsius ? {
        celsius: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
